### PR TITLE
Coredns 1.7.1

### PR DESCRIPTION
**Pull request by ericgraf**
Upversion to upstream coredns version 1.7.1

Release notes: 
- [https://coredns.io/2020/06/15/coredns-1.7.0-release/](https://coredns.io/2020/06/15/coredns-1.7.0-release/) **breaking changes are present**
- [https://coredns.io/2020/09/21/coredns-1.7.1-release/](https://coredns.io/2020/09/21/coredns-1.7.1-release/)

https://github.com/giantswarm/coredns-app/pull/69 needs to be merged and coredns-app needs to be versioned before this change can be merged

### CODE REVIEW

**Comment by stone-z** [comment]
This will need to have `upstream` removed again as it was deprecated in 1.7.0 https://coredns.io/2020/06/15/coredns-1.7.0-release/

**Comment by stone-z** [comment]
I'd be inclined to link to the 1.7.0 release notes as well, since the breaking changes are described there

**Comment by stone-z** [comment]
Also, we [use some of the renamed metrics](https://github.com/giantswarm/g8s-prometheus/blob/22e35cebec662961f8e7d694f56d891d4df2a9eb/helm/g8s-prometheus/prometheus-rules/coredns.rules.yml). Since monitoring isn't versioned with releases, we'll have a period of time with both "old" and "new" metric names floating around. My suggestion* would be to make prometheus use the "new" metric names and apply a relabel rule to rename "old" metrics to the "new" name.

* unless these metrics are significant for Cortex. I don't think they are, but would recommend running it by SIG Monitoring

**Comment by ericgraf** [comment]
> This will need to have `upstream` removed again as it was deprecated in 1.7.0 https://coredns.io/2020/06/15/coredns-1.7.0-release/

Right now master has the option deleted so the diff doesn't show up. But we will have to verify that it is deleted before this is merged.

- [ ] Once https://github.com/giantswarm/coredns-app/pull/69 has been merged make sure `upstream` is removed in this change.

**Comment by stone-z** [comment]
Tested on AWS on `ginger` - cluster passes CNCF conformance with coredns version 1.7.1

**Comment by stone-z** [comment]
Tested on Azure on `ghost` with k8s 1.18 - passed k8s conformance

**Comment by stone-z** [comment]
@giantswarm/team-ludacris PTAL

**Review by MarcelMue — APPROVED** [review]

**Pull request merged**
